name: Deploy Next.js App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Deploy and Restart Application on EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 22 # Default SSH port, adjust if yours is different
        script: |
          set -e # Exit immediately if any command fails

          # Navigate to your application's deployment directory
          # Ensure this path matches where your app is on EC2
          cd /var/www/nextjs-app

          echo "Ensuring clean Git state on EC2: discarding local changes and untracked files..."
          git reset --hard HEAD # Discard any local modifications to tracked files
          git clean -fd          # Remove untracked files and directories

          echo "Pulling latest code from Git (for consistency)..."
          git pull origin main

          # Install ALL Node.js dependencies for both build and runtime on EC2
          # Crucial: DO NOT use --production here, as devDependencies are needed for 'npm run build'
          echo "Installing ALL Node.js dependencies for build and runtime on EC2..."
          npm install

          echo "Building Next.js application on EC2..."
          npm run build

          # Delete the old PM2 process if it exists to ensure a clean restart with updated configurations
          echo "Deleting old PM2 process '${{ secrets.PM2_APP_NAME }}' if it exists..."
          pm2 delete ${{ secrets.PM2_APP_NAME }} || true # `|| true` prevents script from failing if process doesn't exist

          # Start the Next.js application using PM2 with robust settings
          # The `-- run start` ensures PM2 executes the 'start' script defined in package.json
          echo "Starting PM2 process '${{ secrets.PM2_APP_NAME }}' with restart limits..."
          pm2 start npm --name "${{ secrets.PM2_APP_NAME }}" \
            --max-restarts 5 \
            -- run start # Arguments for `npm run start` go after `--`

          # Ensure PM2 saves its current process list for persistence across server reboots
          echo "Saving PM2 process list..."
          pm2 save

          echo "Deployment successful on EC2!"