name: Deploy Next.js to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies (on GitHub Runner - optional but good for CI check)
        run: npm install

      - name: Build Next.js application (on GitHub Runner - optional but good for CI check)
        run: npm run build
        # This build is mainly for checking if the code can build. The real production build
        # with correct env vars will happen on EC2.

      - name: Deploy and Rebuild on EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Ensure the script exits immediately if any command fails
            set -e

            # Navigate to your application's root directory on EC2
            cd /var/www/nextjs-app

            # Pull the latest changes from Git
            echo "Pulling latest code from Git..."
            git pull origin main

            # Reinstall dependencies (in case package.json changed)
            # Ensure this is run in the app directory
            echo "Installing/updating Node.js dependencies..."
            npm install --production

            # Rebuild the Next.js application on the EC2 instance
            # This uses the env vars from .env.production on EC2 and creates the .next folder
            echo "Building Next.js application..."
            npm run build

            # Restart the PM2 process ONLY if the build was successful
            echo "Restarting PM2 process '${{ secrets.PM2_APP_NAME }}'..."
            pm2 restart ${{ secrets.PM2_APP_NAME }}

            # Save PM2 process list
            echo "Saving PM2 process list..."
            pm2 save

            echo "Deployment successful on EC2!"